// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyfvpwnrseavtxlmlzis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5ZnZwd25yc2VhdnR4bG1semlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MzMzOTUsImV4cCI6MjA4OTEwOTM5NX0.J5zoAHmNFky8zK6Jpm9pltGVspdrzl2pqol6FWMQIVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});